#! /bin/sh

# General
trap '' INT TSTP
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep bspswallow || bspswallow &
picom -f &
nitrogen --restore &
systemctl start spice-vdagent
spice-vdagent &

# Monitors and Workplaces
for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    bspc monitor $m -d 1 2 3 4 5 6
done

# Borders
bspc config border_width 6
bspc config right_padding 2
bspc config left_padding 2
bspc config window_gap 10

# Colors
bspc config focused_border_color "#313f55"
bspc config normal_border_color "#141d2b"
bspc config presel_feedback_color "#141d2b"
bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config single_monocle true
bspc config ignore_ewmh_focus true

# Cleanup
bspc rule -r '*'

# My Polybar configs
killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar -q main -c "$HOME/.config/polybar/config.ini" &

# In order for resizing with alt and mouse to work
bspc config pointer_modifier mod1
bspc config pointer_action1 move
